apiVersion: v2
name: envoy-gateway
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: gateway-helm
    alias: gatewayprovider
    version: v1.6.2
    repository: oci://docker.io/envoyproxy
