apiVersion: v2
name: valkey
description: A Helm chart for Kubernetes
type: application
version: 0.1.1
appVersion: 1.16.0
dependencies:
- name: valkey
  version: 0.9.2
  repository: https://valkey.io/valkey-helm/
