apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-querier
  namespace: {{ .Values.namespace }}
  labels:
    app: thanos-querier
spec:
  replicas: {{ .Values.thanos.query.replicas }}
  selector:
    matchLabels:
      app: thanos-querier
  template:
    metadata:
      labels:
        app: thanos-querier
    spec:
      containers:
      - name: thanos
        image: {{ .Values.thanos.image }}
        args:
        - query
        - --log.level=debug
        - --query.replica-label=prometheus_replica
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:9090
        - --store=dnssrv+thanos-store-gateway:10901
      {{- range $key, $value := .Values.thanos.query.extraArgs }}
        - --{{ $key }}={{ $value }}
      {{- end }}
        ports:
        - name: http
          containerPort: 9090
        - name: grpc
          containerPort: 10901
        livenessProbe:
          httpGet:
            port: http
            path: /-/healthy
        readinessProbe:
          httpGet:
            port: http
            path: /-/ready
        resources:
          {{- toYaml .Values.thanos.query.resources | nindent 10 }}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-querier
  name: thanos-querier
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.thanos.query.service.type }}
  ports:
  - port: 9090
    protocol: TCP
    targetPort: http
    name: http
  selector:
    app: thanos-querier
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-querier
  name: thanos-querier-scrape
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 10901
    protocol: TCP
    targetPort: grpc
    name: grpc
  selector:
    app: thanos-querier
