cluster:
  env: dev
  name: dev-01
  server: https://dev-01-k8s.endpoint.kubernetes

source:
  targetRevision: master
  helm:
    valueFiles: values.dev-01.yaml

sealedSecrets:  # targetRevision and valueFiles can be overridden here if the above defaults are not suitable
  enable: true

envoyGateway:
  enable: true

externalDNS:
  enable: true

certManager:
  enable: true

monitoring:
  enable: true

logging:
  enable: true

jaeger:
  enable: true

kyverno:
  enable: true

redis:
  enable: true

valkey:
  enable: true
