apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: external-dns
version: 0.1.0
dependencies:
- name: external-dns
  version: 1.20.0
  repository: https://kubernetes-sigs.github.io/external-dns/