namespace: external-dns
kubernetesProvider: GKE

external-dns:
  logLevel: info
  logFormat: json
  interval: 5m
  provider: google
  sources:
  - service
  - gateway-httproute
  - gateway-grpcroute
  resources:
    limits:
      cpu: 500m
      memory: 300Mi
    requests:
      cpu: 20m
      memory: 75Mi
  env:
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: /var/secrets/google/external-dns-credentials.json
  extraVolumes:
  - name: google-cloud-key
    secret:
      secretName: external-dns-credentials
  extraVolumeMounts:
  - name: google-cloud-key
    mountPath: /var/secrets/google

sealedCredentials: "" # SealedSecret value for external-dns-credentials.json
