apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: gcp-dns-credentials
  namespace: cert-manager
spec:
  encryptedData:
    gcp-dns-credentials.json: 
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: gcp-dns-credentials
      namespace: cert-manager
    type: Opaque
