trivy:
  skipcharts:
    - argo-apps
    - nginx-ingress-controller # not enabled anywhere
    - jaeger # upstream chart has some vulnerabilities for which fix is not available
    - kyverno # Trivy unable to scan

  skipimages:
    -  lmenezes/cerebro:0.9.4 # Fix not available
    -  bitnami/kubectl:1.30.2 # Fix not available
    -  quay.io/google-cloud-tools/kube-eagle:1.1.4 # Fix not available
    -  docker.io/bitnami/redis:8.0.3-debian-12-r1 # Fix not available
    -  emberstack/kubernetes-reflector:7.1.262 # Fix not available
    -  vaibhavthakur/utils:v0.3 # Custom image, not updating for now

checkov:
  skipcharts:
    - argo-apps
    - kyverno # Upstream chart has hooks which does not support all configs
    - eck-operator # skipping since upstream chart does not support all configs

