apiVersion: v2
name: sealed-secrets
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: sealed-secrets
    alias: sealedSecrets
    version: 2.17.9
    repository: https://bitnami-labs.github.io/sealed-secrets
