global:
  resolve_timeout: 5m
  slack_api_url: "<your_slack_hook>"
  victorops_api_url: "<your_victorops_hook>"

templates:
- '/etc/alertmanager-templates/*.tmpl'
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 5m  
  receiver: default 
  routes:
  - match:
      team: devops
    receiver: devops
    continue: true 
  - match: 
      team: dev
    receiver: dev
    continue: true

receivers:
- name: 'default'

- name: 'devops'
  victorops_configs:
  - api_key: '<YOUR_API_KEY>'
    routing_key: 'devops'
    message_type: 'CRITICAL'
    entity_display_name: '{{ .CommonLabels.alertname }}'
    state_message: 'Alert: {{ .CommonLabels.alertname }}. Summary:{{ .CommonAnnotations.summary }}. RawData: {{ .CommonLabels }}'
  slack_configs:
  - channel: '#k8-alerts'
    send_resolved: true


- name: 'dev'
  victorops_configs:
  - api_key: '<YOUR_API_KEY>'
    routing_key: 'dev'
    message_type: 'CRITICAL'
    entity_display_name: '{{ .CommonLabels.alertname }}'
    state_message: 'Alert: {{ .CommonLabels.alertname }}. Summary:{{ .CommonAnnotations.summary }}. RawData: {{ .CommonLabels }}'
  slack_configs:
  - channel: '#k8-alerts'
    send_resolved: true  